language: r
os: osx
r:
- release
- devel
env:
- _R_CHECK_FORCE_SUGGESTS_=false
sudo: false
cache: packages
warnings_are_errors: false
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then tlmgr install anysize; fi
addons:
  apt:
    packages:
    - libgsl0-dev
    - bwidget
brew_packages:
- gsl
after_success:
- if [[ "$TRAVIS_R_VERSION" != "devel" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
deploy:
  provider: releases
  api_key:
    secure: ClD8ervG1XqpUlcx61m1DScZz8gTORHtVjQqepLfSDsdBq0Jr4fNgQ3HJSWYO7kqm2VVz5WN1KAl83WrOereirQZjHAVmiIwnA769RohxCupc+6tIXfJvJF64V+RX001+ZcboKdFTYhsAe8kbdVbrUOoeo/edx3fvvJTflpYk/oTqIe4IVLG6OM1VyM/XhfRM1n0PnjlLxFfWxM4xtcxwfKfdXN1SQaqIuncyHQB/sgpqXkQV9GnHJNZ0eucopmh8a7IUgqh5vJqRiC4+ioP1GdxvAvhE0p8VkJaOiy46MPjM5Jghg4K26KDgRXhtlR9iaovI58zds0pL5QI3uevxuPtYYqW1AQ0/qGzpLCDKWHutilGNusT6cQhIYxpo/bS875DXExBN4G3NuHJOXW6lxO0bYNWh+3LpU8tamp2E76+JuNSWHZISxLbU965N45DoYJh8BkIzMUJUTlF9OlUnK5B3eeCigaKqk/y23f6qEg0SmOsK5rA+dI6qS6xl6ZpC0F6nugwS/YHWKQlNG9R02U8WSy0frrSYFoWD50nIfm2cvbGcwT723L5JSlJoNutjGNsS7Gug+H828mbPbR8/ZAFvBruOPUKJlPlh4d/8HD3CJoTxVTE18GzJRIfyxuwhVk/4Y7kAklULEsBwGku4JqCBzE9Vvu99JLqJkrTW/A=
  skip_cleanup: true
  file_glob: true
  file: spatstat_*.t*gz
  on:
    tags: true
    condition: "$TRAVIS_R_VERSION != devel && ($TRAVIS_OS_NAME == osx)"
