# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
  matrix:
  - R_CODECOV_TEST=true
  - R_CODECOV_EXAMPLE=true
  - R_CODECOV_VIGNETTE=true BOOTSTRAP_LATEX=true

sudo: required

dist: trusty

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-deldir r-cran-abind r-cran-tensor r-cran-polyclip r-cran-goftest
  - ./run.sh install_aptget r-cran-sm r-cran-maptools r-cran-gsl r-cran-locfit r-cran-spatial r-cran-tkrplot r-cran-randomfields r-cran-randomfieldsutils r-cran-fftwtools
  - ./run.sh install_aptget r-cran-covr r-cran-devtools
  - ./run.sh install_aptget texinfo
  - ./run.sh install_github spatstat/spatstat.utils spatstat/spatstat.data

script:
  - cd ../..
  - rm -rf spatstat/spatstat
  - git clone --depth=50 --branch=master https://github.com/spatstat/spatstat.git spatstat/spatstat
  - cd spatstat/spatstat
  - if [[ "${R_CODECOV_TEST}" ]]; then R -e 'covr::codecov(type = "test", quiet = FALSE, commit = covr:::current_commit(), branch = covr:::local_branch())'; fi
  - if [[ "${R_CODECOV_EXAMPLE}" ]]; then R -e 'covr::codecov(type = "example", quiet = FALSE, commit = covr:::current_commit(), branch = covr:::local_branch())'; fi
  - if [[ "${R_CODECOV_VIGNETTE}" ]]; then R -e 'covr::codecov(type = "vignette", quiet = FALSE, commit = covr:::current_commit(), branch = covr:::local_branch())'; fi

notifications:
  email:
    on_success: change
    on_failure: change

